(()=>{const norm=s=>(s||"").toString().trim().toLowerCase();let cache;
function root(){for(const s of document.querySelectorAll("script[src]")){let x=s.getAttribute("src")||"";if(x.includes("assets/javascripts"))try{return new URL(x,location.href).pathname.split("/assets/javascripts/")[0].replace(/\/$/,"")}catch(e){}}return""}
const R=root();async function docs(){return cache||(cache=fetch(`${R}/search/search_index.json`,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(x=>x.docs||[]))}
function score(d,q){let t=norm(d.title),x=norm(d.text),l=norm(d.location),n=0;if(t===q)n+=120;if(t.startsWith(q))n+=70;if(t.includes(q))n+=50;if(l.includes(q))n+=18;if(x.includes(q))n+=12;return n}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function excerpt(s,q){s=(s||"").replace(/\s+/g," ").trim();let p=s.toLowerCase().indexOf(q),a=Math.max(0,p<0?0:p-38),v=s.slice(a,a+105);return(a?"…":"")+v+(a+105<s.length?"…":"")}
function href(l){if(/^https?:\/\//i.test(l||""))return l;return`${R}/${(l||"").replace(/^\/+/,"")}`}
function init(input){if(input.dataset.ddReady)return;input.dataset.ddReady="1";let box=input.closest(".top-search")||input.parentElement;if(!box)return;box.querySelectorAll("kbd,.search-key,.key,.shortcut").forEach(x=>x.remove());input.autocomplete="off";input.placeholder="搜索攻略、角色、地图等…";let p=document.createElement("div");p.className="dd-search-results";p.hidden=true;box.appendChild(p);let found=[],timer;
const close=()=>{p.hidden=true;p.innerHTML="";found=[]};
async function run(){let q=norm(input.value);if(!q)return close();p.hidden=false;p.innerHTML='<div class="dd-search-state">SEARCHING / 搜索中…</div>';try{let ds=await docs();found=ds.map(d=>[d,score(d,q)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>x[0]);p.innerHTML=found.length?found.map((d,i)=>`<a class="dd-search-item" href="${href(d.location)}"><span class="dd-search-no">${String(i+1).padStart(2,"0")}</span><span class="dd-search-copy"><b>${esc(d.title||"未命名页面")}</b><small>${esc(excerpt(d.text,q))}</small></span><span class="dd-search-arrow">↗</span></a>`).join(""):'<div class="dd-search-state"><b>NO RESULT</b><span>没有找到相关内容</span></div>'}catch(e){p.innerHTML='<div class="dd-search-state"><b>SEARCH ERROR</b><span>搜索索引加载失败</span></div>'}}
input.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(run,90)});input.addEventListener("keydown",e=>{if(e.key==="Escape"){close();input.blur()}if(e.key==="Enter"&&found[0]){e.preventDefault();location.href=href(found[0].location)}});document.addEventListener("click",e=>{if(!box.contains(e.target))close()})}
function boot(){let i=document.querySelector("#heroSearch,.top-search input");if(i)init(i)}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot):boot()})();